name: Run Watchlist Notification

on:
  schedule:
    - cron: '0 5 * * 1'  # Every Monday at 12 pm WIB (5 am UTC)
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Watchlist Notification API
        run: |
          curl -X GET "https://sectors-watchlist-notification.vercel.app/api/email" \
            -H "Authorization: Bearer ${{ secrets.SECRET }}"
